# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('birdDate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.CharField(max_length=50)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Departament')),
            ],
        ),
    ]
